# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Mayven' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChatApp
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage' 
  pod 'Firebase/Database' 
  pod 'Firebase/Functions'
  pod 'BetterSegmentedControl'
  pod 'Firebase/Messaging'
  pod 'Google-Mobile-Ads-SDK'
  pod 'SDWebImage'
  pod 'FloatingPanel'
  pod 'SwiftLinkPreview'

end
